export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

// Category Types
export const CATEGORY_FETCH_REQUEST = 'CATEGORY_FETCH_REQUEST';
export const CATEGORY_FETCH_SUCCESS = 'CATEGORY_FETCH_SUCCESS';
export const CATEGORY_FETCH_FAIL = 'CATEGORY_FETCH_FAIL';

export const CATEGORY_CREATE_REQUEST = 'CATEGORY_CREATE_REQUEST';
export const CATEGORY_CREATE_SUCCESS = 'CATEGORY_CREATE_SUCCESS';
export const CATEGORY_CREATE_FAIL = 'CATEGORY_CREATE_FAIL';

export const CATEGORY_UPDATE_REQUEST = 'CATEGORY_UPDATE_REQUEST';
export const CATEGORY_UPDATE_SUCCESS = 'CATEGORY_UPDATE_SUCCESS';
export const CATEGORY_UPDATE_FAIL = 'CATEGORY_UPDATE_FAIL';

export const CATEGORY_DELETE_REQUEST = 'CATEGORY_DELETE_REQUEST';
export const CATEGORY_DELETE_SUCCESS = 'CATEGORY_DELETE_SUCCESS';
export const CATEGORY_DELETE_FAIL = 'CATEGORY_DELETE_FAIL';

// Product Types
export const PRODUCT_FETCH_REQUEST = "PRODUCT_FETCH_REQUEST";
export const PRODUCT_FETCH_SUCCESS = "PRODUCT_FETCH_SUCCESS";
export const PRODUCT_FETCH_FAIL = "PRODUCT_FETCH_FAIL";

export const PRODUCT_CREATE_REQUEST = "PRODUCT_CREATE_REQUEST";
export const PRODUCT_CREATE_SUCCESS = "PRODUCT_CREATE_SUCCESS";
export const PRODUCT_CREATE_FAIL = "PRODUCT_CREATE_FAIL";

export const PRODUCT_UPDATE_REQUEST = "PRODUCT_UPDATE_REQUEST";
export const PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS";
export const PRODUCT_UPDATE_FAIL = "PRODUCT_UPDATE_FAIL";

export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST";
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
export const PRODUCT_DELETE_FAIL = "PRODUCT_DELETE_FAIL";

// Variant Option Types
export const VARIANT_OPTION_FETCH_REQUEST = 'VARIANT_OPTION_FETCH_REQUEST';
export const VARIANT_OPTION_FETCH_SUCCESS = 'VARIANT_OPTION_FETCH_SUCCESS';
export const VARIANT_OPTION_FETCH_FAIL = 'VARIANT_OPTION_FETCH_FAIL';

export const VARIANT_OPTION_CREATE_REQUEST = 'VARIANT_OPTION_CREATE_REQUEST';
export const VARIANT_OPTION_CREATE_SUCCESS = 'VARIANT_OPTION_CREATE_SUCCESS';
export const VARIANT_OPTION_CREATE_FAIL = 'VARIANT_OPTION_CREATE_FAIL';

export const VARIANT_OPTION_UPDATE_REQUEST = 'VARIANT_OPTION_UPDATE_REQUEST';
export const VARIANT_OPTION_UPDATE_SUCCESS = 'VARIANT_OPTION_UPDATE_SUCCESS';
export const VARIANT_OPTION_UPDATE_FAIL = 'VARIANT_OPTION_UPDATE_FAIL';

export const VARIANT_OPTION_DELETE_REQUEST = 'VARIANT_OPTION_DELETE_REQUEST';
export const VARIANT_OPTION_DELETE_SUCCESS = 'VARIANT_OPTION_DELETE_SUCCESS';
export const VARIANT_OPTION_DELETE_FAIL = 'VARIANT_OPTION_DELETE_FAIL';

// Order Types
export const ORDER_FETCH_REQUEST = "ORDER_FETCH_REQUEST";
export const ORDER_FETCH_SUCCESS = "ORDER_FETCH_SUCCESS";
export const ORDER_FETCH_FAIL = "ORDER_FETCH_FAIL";

export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";

export const ORDER_UPDATE_STATUS_REQUEST = "ORDER_UPDATE_STATUS_REQUEST";
export const ORDER_UPDATE_STATUS_SUCCESS = "ORDER_UPDATE_STATUS_SUCCESS";
export const ORDER_UPDATE_STATUS_FAIL = "ORDER_UPDATE_STATUS_FAIL";

export const ORDER_DELETE_REQUEST = "ORDER_DELETE_REQUEST";
export const ORDER_DELETE_SUCCESS = "ORDER_DELETE_SUCCESS";
export const ORDER_DELETE_FAIL = "ORDER_DELETE_FAIL";